### ISSUE TITLE
Fix deploy to GH Pages

### ISSUE THREAD

**Issue by gaearon** [dvampofo/bullentin-board#2]
You can remove all the hacks with hardcoding the URLs in index.html as suggested on Reddit. Instead you need to add `"homepage": "https://dvampofo.github.io/bullentin-board"` to your `package.json` as mentioned in User Guide and in the build console output. Then the next time you run `npm run build` it will be built with the correct prefix and you can deploy it. I hope this helps!

**Comment by dvampofo** [comment]
@gaearon Thanks for the advice Dan. I see that `"homepage": "https://dvampofo.github.io/bullentin-board"` was already part of my `package.json` file. The issue that another user found was that I had additional `/` in my `build/index.html` and that I had to move my script tag (`build/static/js/main.285cfe90.js``) in``public/index.html``to the``body`` area.

**Comment by gaearon** [comment]
Let me clarify again: you did **not** need to do any manual adjustments like changing script tags. The person who suggested this on Reddit didn't know how Create React App works. This was wrong advice.

**Comment by gaearon** [comment]
The HTML file in the build folder is generated automatically. Its script path is inferred from the homepage setting. So if you set it, the next build would be done with the correct path. You never need to touch the output HTML file manually or hardcore JS paths there (in fact this will break as soon as you change any code because the hash will be different).

If you had troubles getting homepage inference working please **file an issue**. It's the only way for us to figure out what went wrong.

**Comment by dvampofo** [comment]
@gaearon 

`The person who suggested this on Reddit didn't know how Create React App works`

Neither do I, but it's a learning process since Im new to using React (and programming). Where is the link where I would file an issue?

**Comment by gaearon** [comment]
> Neither do I

Sorry, I didn't mean to imply there's something wrong with not knowing. I just meant that you shouldn't rely on that advice because it was wrong.

**Comment by gaearon** [comment]
> Where is the link where I would file an issue?

It's in the README you [deleted](https://github.com/dvampofo/bullentin-board/commit/e16241399ef101406641af6a1b20387884224e8b#diff-04c6e90faac2675aa89e2176d2eec7d8L71):

https://github.com/facebookincubator/create-react-app/issues/new
